import { Contact, Message, Call, Reminder, ChatMessage } from "./types";

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Mom",
    phone: "+1 (555) 123-4567",
    email: "mom@email.com",
    isFavorite: true,
    tags: ["Family"],
    lastMessage: "2 hours ago",
    lastCall: "Today, 2:30pm",
  },
  {
    id: "2",
    name: "Giuseppe",
    phone: "+1 (555) 234-5678",
    email: "giuseppe@email.com",
    isFavorite: true,
    tags: ["Family", "Work"],
    notes: "Brother, lives in NYC",
    lastMessage: "1 hour ago",
    lastCall: "Today, 11:15am",
  },
  {
    id: "3",
    name: "Sarah Johnson",
    phone: "+1 (555) 345-6789",
    email: "sarah@email.com",
    isFavorite: false,
    tags: ["Work"],
    lastMessage: "Yesterday",
  },
  {
    id: "4",
    name: "Alex Wong",
    phone: "+1 (555) 456-7890",
    isFavorite: false,
    tags: ["Friend"],
    lastMessage: "3 days ago",
  },
  {
    id: "5",
    name: "FedEx Delivery",
    phone: "+1 (800) 463-3339",
    isFavorite: false,
    tags: ["Delivery Service"],
    lastMessage: "Today",
  },
];

export const mockMessages: Message[] = [
  {
    id: "1",
    contactId: "1",
    contactName: "Mom",
    content: "Don't forget dinner tonight!",
    timestamp: "2:30pm",
    isIncoming: true,
    status: "priority",
    rule: "Family",
    isRead: false,
  },
  {
    id: "2",
    contactId: "5",
    contactName: "FedEx Delivery",
    content: "Your package will arrive tomorrow between 2-4pm.",
    timestamp: "1:15pm",
    isIncoming: true,
    status: "allowed",
    rule: "Delivery Service",
    isRead: true,
  },
  {
    id: "3",
    contactId: "unknown",
    contactName: "Unknown Number",
    content: "We've been trying to reach you about your car's extended warranty...",
    timestamp: "12:05pm",
    isIncoming: true,
    status: "blocked",
    rule: "Spam Detected",
    isRead: true,
  },
  {
    id: "4",
    contactId: "2",
    contactName: "Giuseppe",
    content: "Hey, can we meet tomorrow?",
    timestamp: "11:30am",
    isIncoming: true,
    status: "priority",
    rule: "Family",
    isRead: false,
  },
];

export const mockChatHistory: Record<string, ChatMessage[]> = {
  "2": [
    { id: "c1", content: "Hey, how's it going?", isIncoming: true, timestamp: "10:00am" },
    { id: "c2", content: "Good! Just finishing up some work", isIncoming: false, timestamp: "10:05am" },
    { id: "c3", content: "Nice! Want to grab lunch later?", isIncoming: true, timestamp: "10:10am" },
    { id: "c4", content: "Sure, what time works for you?", isIncoming: false, timestamp: "10:15am" },
    { id: "c5", content: "How about 1pm?", isIncoming: true, timestamp: "10:20am" },
    { id: "c6", content: "Perfect, see you then!", isIncoming: false, timestamp: "10:25am" },
    { id: "c7", content: "Hey, can we meet tomorrow?", isIncoming: true, timestamp: "11:30am" },
  ],
  "1": [
    { id: "m1", content: "Hi sweetie, are you free for dinner tonight?", isIncoming: true, timestamp: "1:00pm" },
    { id: "m2", content: "Yes mom, what time?", isIncoming: false, timestamp: "1:30pm" },
    { id: "m3", content: "7pm at the usual place. Don't forget dinner tonight!", isIncoming: true, timestamp: "2:30pm" },
  ],
};

export const mockCalls: Call[] = [
  {
    id: "1",
    contactId: "1",
    contactName: "Mom",
    phone: "+1 (555) 123-4567",
    timestamp: "Today, 2:30pm",
    type: "outgoing",
    duration: "12m 34s",
  },
  {
    id: "2",
    contactId: "2",
    contactName: "Giuseppe",
    phone: "+1 (555) 234-5678",
    timestamp: "Today, 11:15am",
    type: "incoming",
    duration: "5m 12s",
  },
  {
    id: "3",
    contactId: "unknown",
    contactName: "Unknown Number",
    phone: "+1 (555) 999-8888",
    timestamp: "Yesterday",
    type: "missed",
    isBlocked: true,
  },
  {
    id: "4",
    contactId: "3",
    contactName: "Sarah Johnson",
    phone: "+1 (555) 345-6789",
    timestamp: "Yesterday",
    type: "outgoing",
    duration: "3m 45s",
  },
];

export const mockReminders: Reminder[] = [
  {
    id: "1",
    type: "personal",
    title: "Exam reminder",
    datetime: "Tomorrow, 6:00 PM",
    isCompleted: false,
    repeat: "never",
  },
  {
    id: "2",
    type: "call",
    title: "Call with Giuseppe",
    datetime: "Dec 27, 3:00 PM",
    contactId: "2",
    contactName: "Giuseppe",
    isCompleted: false,
  },
  {
    id: "3",
    type: "message",
    title: "Send 'Happy Birthday' to Mom",
    datetime: "Dec 28, 9:00 AM",
    contactId: "1",
    contactName: "Mom",
    isCompleted: false,
  },
];

export const languages = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
];